version: 2
updates:
- package-ecosystem: nuget
  directory: "/test"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/samples/current"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/samples/2.1"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "Microsoft.*"
      versions: ["(,3.0)"]
  open-pull-requests-limit: 10
